# Generated by Django 4.2 on 2023-04-24 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Truck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_plate", models.CharField(max_length=50, unique=True)),
                ("registration_number", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("mobile_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("city", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("language", models.CharField(max_length=50)),
                (
                    "assigned_truck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="driver_api.truck",
                    ),
                ),
            ],
        ),
    ]
